packages:
  - javascript
  - typescript

allowBuilds:
  '@tailwindcss/oxide': false
  better-sqlite3: false
  esbuild: false

minimumReleaseAgeExclude:
  - sv
  - '@sveltejs/sv-utils'
  - '@sveltejs/adapter-auto@8.0.0'
  - '@sveltejs/kit@3.0.0'
